$(function() {
    $(".information").click(function() {
        $(".card__main").css({'display': 'flex'})
        $(".information--fa").css({'color': '#fbfbfb'})
        $(".information--text").css({'color': '#fbfbfb'})
        $(".card__third").css({'display': 'none'})
        $(".buy--fa").css({'color': '#b7bacd'})
        $(".buy--text").css({'color': '#b7bacd'})
        $(".card__second").css({'display': 'none'})
        $(".ratings--fa").css({'color': '#b7bacd'})
        $(".ratings--text").css({'color': '#b7bacd'})
    })
    $(".ratings").click(function() {
        $(".card__second").css({'display': 'flex'})
        $(".ratings--fa").css({'color': '#fbfbfb'})
        $(".ratings--text").css({'color': '#fbfbfb'})
        $(".card__main").css({'display': 'none'})
        $(".information--fa").css({'color': '#b7bacd'})
        $(".information--text").css({'color': '#b7bacd'})
        $(".card__third").css({'display': 'none'})
        $(".buy--fa").css({'color': '#b7bacd'})
        $(".buy--text").css({'color': '#b7bacd'})
    })
    $(".buy").click(function() {
        $(".card__third").css({'display': 'flex'})
        $(".buy--fa").css({'color': '#fbfbfb'})
        $(".buy--text").css({'color': '#fbfbfb'})
        $(".card__second").css({'display': 'none'})
        $(".ratings--fa").css({'color': '#b7bacd'})
        $(".ratings--text").css({'color': '#b7bacd'})
        $(".card__main").css({'display': 'none'})
        $(".information--fa").css({'color': '#b7bacd'})
        $(".information--text").css({'color': '#b7bacd'})
    })
})